---
version: "3.4"
services:
  web:
    image: "uwcirg/cosri-patientsearch:${DOCKER_IMAGE_TAG:-develop}"
    build:
      context: .
      args:
        # set build arg from environment variable with same name
        # add default to squelch warnings
        REACT_APP_VERSION_STRING: ${REACT_APP_VERSION_STRING:-local}
    ports:
      # allow override of published port
      - ${EXTERNAL_PORT:-8000}:8000
    env_file:
      - patientsearch.env
    volumes:
      - ./client_secrets.json:/opt/cosri-patientsearch/client_secrets.json:ro
