# docker-compose development overrides
# mount code checkout into container and use development server for auto-reloading
---
version: "3.4"
services:
  web:
    environment:
      FLASK_ENV: development
    volumes:
      - ./:/opt/cosri-patientsearch
    command: flask run --host 0.0.0.0 --port 8000
