---
version: "3.4"
services:
  web:
    image: "uwcirg/cosri-patientsearch:${DOCKER_IMAGE_TAG:-develop}"
    build:
      context: .
    ports:
      # allow override of published port
      - ${EXTERNAL_PORT:-8000}:8000
    env_file:
      - patientsearch.env
    volumes:
      - ./client_secrets.json:/opt/cosri-patientsearch/client_secrets.json:ro
